file_mappings:
  sample_bank_statement.csv: chase_checking
accounts:
  chase_checking:
    name: Chase Checking ****1234
    type: checking
    institution: Chase
    account_number_masked: '1234'
    opening_balance_date: '2024-01-01'
    source_file_patterns:
    - '*chase*checking*.csv'
    - '*chase*checking*.ofx'
    display_order: 1
  amex_gold:
    name: Amex Gold ****5678
    type: credit_card
    institution: American Express
    account_number_masked: '5678'
    opening_balance: '-2500.0'
    opening_balance_date: '2024-01-01'
    source_file_patterns:
    - '*amex*.csv'
    - '*amex*.ofx'
    - '*american_express*.csv'
    display_order: 2
  ally_savings:
    name: Ally Savings ****9012
    type: savings
    institution: Ally Bank
    account_number_masked: '9012'
    opening_balance: '10000.0'
    opening_balance_date: '2024-01-01'
    source_file_patterns:
    - '*ally*.csv'
    - '*ally*.ofx'
    display_order: 3
  fidelity_brokerage:
    name: Fidelity Brokerage ****3456
    type: investment
    institution: Fidelity
    account_number_masked: '3456'
    source_file_patterns:
    - '*fidelity*.csv'
    display_order: 10
  coinbase_wallet:
    name: Coinbase Wallet
    type: crypto
    institution: Coinbase
    source_file_patterns:
    - '*coinbase*.csv'
    display_order: 20
